name: Calender CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # or your required version
          cache: 'npm'
          cache-dependency-path: frontend/package.json

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Run Tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Build Angular App
        run: npm run build
